--DELETE FOREIGN KEYS SO TABLES CAN BE DELETED
IF OBJECT_ID('FK_Employee_ZipCity', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Employee DROP CONSTRAINT FK_Employee_ZipCity END;
IF OBJECT_ID('FK_Manager_Department', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Manager DROP CONSTRAINT FK_Manager_Department END;
IF OBJECT_ID('FK_Manager_Employee', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Manager DROP CONSTRAINT FK_Manager_Employee END;
IF OBJECT_ID('FK_Customer_ZipCity', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Customer DROP CONSTRAINT FK_Customer_ZipCity END;
IF OBJECT_ID('FK_Employee_Department', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Employee DROP CONSTRAINT FK_Employee_Department END;
IF OBJECT_ID('FK_Order_Customer', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_Order DROP CONSTRAINT FK_Order_Customer END;
IF OBJECT_ID('FK_OrderLine_Product', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_OrderLine DROP CONSTRAINT FK_OrderLine_Product END;
IF OBJECT_ID('FK_OrderLine_Order', 'F') IS NOT NULL BEGIN ALTER TABLE EX62_OrderLine DROP CONSTRAINT FK_OrderLine_Order END;

--DELETE TABLE IF THEY EXIST SO THEY CAN BE RECREATED
IF OBJECT_ID('EX62_ZipCity', 'U') IS NOT NULL BEGIN DROP TABLE EX62_ZipCity END;
IF OBJECT_ID('EX62_Employee', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Employee END;
IF OBJECT_ID('EX62_Customer', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Customer END;
IF OBJECT_ID('EX62_Department', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Department END;
IF OBJECT_ID('EX62_Manager', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Manager END;
IF OBJECT_ID('EX62_Product', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Product END;
IF OBJECT_ID('EX62_Order', 'U') IS NOT NULL BEGIN DROP TABLE EX62_Order END;
IF OBJECT_ID('EX62_OrderLine', 'U') IS NOT NULL BEGIN DROP TABLE EX62_OrderLine END;

--CREATE TABLES, PRIMARY KEYS AND FOREIGN KEYS
CREATE TABLE EX62_ZipCity (
	Zip NVARCHAR(4) PRIMARY KEY NOT NULL, 
	City NVARCHAR(40) NOT NULL
)

CREATE TABLE EX62_Employee
(
	Emp_Id INTEGER IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FName NVARCHAR(40),
	LName NVARCHAR(40),
	Dep_Id INTEGER,
	Zip NVARCHAR(4)
)

ALTER TABLE EX62_Employee
ADD CONSTRAINT FK_Employee_ZipCity 
	FOREIGN KEY(Zip) REFERENCES EX62_ZipCity(Zip)
	ON UPDATE CASCADE
	ON DELETE SET NULL;

CREATE TABLE EX62_Department
(
	Dep_Id INTEGER IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Dept_Name NVARCHAR(50) NOT NULL,
)

ALTER TABLE EX62_Employee
ADD CONSTRAINT FK_Employee_Department 
	FOREIGN KEY(Dep_Id) REFERENCES EX62_Department(Dep_Id)
	ON UPDATE CASCADE
	ON DELETE SET NULL;

CREATE TABLE EX62_Manager
(
	Dep_Id INTEGER NOT NULL,
	Manager INTEGER NOT NULL
)

ALTER TABLE EX62_Manager
ADD CONSTRAINT PK_Manager
	PRIMARY KEY (Dep_Id, Manager);

ALTER TABLE EX62_Manager
ADD CONSTRAINT FK_Manager_Department 
	FOREIGN KEY(Dep_Id) REFERENCES EX62_Department(Dep_Id)
	ON UPDATE CASCADE;

ALTER TABLE EX62_Manager
ADD CONSTRAINT FK_Manager_Employee 
	FOREIGN KEY(Manager) REFERENCES EX62_Employee(Emp_Id);

CREATE TABLE EX62_Customer
(
	Customer_Id INTEGER IDENTITY PRIMARY KEY NOT NULL, 
	FName NVARCHAR(40),
	LName NVARCHAR(40),
	Zip NVARCHAR(4)
)

ALTER TABLE EX62_Customer
ADD CONSTRAINT FK_Customer_ZipCity 
	FOREIGN KEY(Zip) REFERENCES EX62_ZipCity(Zip)
	ON UPDATE CASCADE
	ON DELETE SET NULL;

CREATE TABLE EX62_Product
(
	Product_Id INTEGER IDENTITY PRIMARY KEY NOT NULL, 
	Prod_Name NVARCHAR(80) NOT NULL DEFAULT N'Name missing', 
	Price DECIMAL NOT NULL DEFAULT 0.00
)

CREATE TABLE EX62_Order
(
	Order_Id INTEGER IDENTITY PRIMARY KEY NOT NULL, 
	Customer INTEGER,
	Order_Date DATETIME2 NOT NULL DEFAULT '01-JAN-2000',
	Paid BIT NOT NULL DEFAULT 0
)

ALTER TABLE EX62_Order
ADD CONSTRAINT FK_Order_Customer
	FOREIGN KEY(Customer) REFERENCES EX62_Customer(Customer_Id)
	ON UPDATE CASCADE
	ON DELETE SET NULL;

CREATE TABLE EX62_OrderLine
(
	Order_Id INTEGER NOT NULL, 
	Product_Id INTEGER NOT NULL,
	Amount INTEGER NOT NULL DEFAULT 0
)

ALTER TABLE EX62_OrderLine
ADD CONSTRAINT FK_OrderLine_Product 
	FOREIGN KEY(Product_Id) REFERENCES EX62_Product(Product_Id)
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

ALTER TABLE EX62_OrderLine
ADD CONSTRAINT FK_OrderLine_Order
	FOREIGN KEY(Order_Id) REFERENCES EX62_Order(Order_Id)
	ON UPDATE CASCADE
	ON DELETE NO ACTION;