CREATE TABLE Timesheet_Task(
SheetID		int			NOT NULL,
TaskID		int			Not NUll,
--
CONSTRAINT	TIMETASK_PK		PRIMARY KEY(SheetID, TaskID),
CONSTRAINT	SHEET_FK		FOREIGN KEY(SheetID)
			REFERENCES		Timesheet(SheetID),
CONSTRAINT	TASK_FK			FOREIGN KEY(TaskID)
			REFERENCES		Task(TaskID)
)